# yaml-language-server: $schema=https://uniform.app/schemas/json-schema/component-definition/v1.json
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productImageGallery
name: Product Image Gallery
icon: screen
parameters:
  - id: images
    name: Images
    type: asset
    guidance: Upload multiple product images. The first image will be shown initially.
    typeConfig:
      allowedTypes:
        - image
  - id: productName
    name: Product Name
    type: text
    guidance: Product name used for image alt text accessibility.
    localizable: true
description: >-
  Interactive product image carousel with thumbnails, navigation arrows, and
  image counter for product detail pages.
useTeamPermissions: true
slots: []
titleParameter: productName
thumbnailParameter: images
canBeComposition: false
created: '2025-12-11T10:21:17.84351+00:00'
updated: '2025-12-11T10:21:17.84351+00:00'
