id: productList
displayName: Product List
path: /query
custom:
  allowedContentTypes:
    - product
method: GET
purgeKey: f661ff8d-0876-4621-ac5f-cf9ec855e70f
archetype: queryEntries
variables:
  limit:
    type: text
    default: '20'
  offset:
    type: text
    default: '0'
  search:
    type: text
    default: ''
  filters:
    type: text
    default: '{}'
  orderBy:
    type: text
    default: ''
  contentTypes:
    type: text
    default: ''
dataSourceId: uniformContent
allowedOnComponents: []
